### ISSUE TITLE
library not found for -lbdIMADpj

### ISSUE THREAD

**Issue by neonsamuel** [saravanandm/pjsip2.5-g729codec#2]
Hello saravanandm,
First of all **BIG Thanks** for the share pjsip2.5-g729codec Patches It's more help me to integrate g729 into PJSip2.5.

But I am little bit stuck into 'lbdIMADpj' library not found issue if you can help me out to solve this issue.
I follow your all patches information and steps all.

Here I attached the screen shot for that.

When I fire below command it's successfully done.

`ARCH="-arch i386" CFLAGS="-O2 -m32 -mios-simulator-version-min=9.3" LDFLAGS="-O2 -m32 -mios-simulator-version-min=9.3" ./configure-iphone`

![screen shot 2016-06-13 at 6 13 01 pm](https://cloud.githubusercontent.com/assets/19908883/16007886/8e8c8a4a-3192-11e6-8c8a-d48adf1f051f.png)

Then after I fire following command and few processing happened and gives error attached into image.
`make dep`
![screen shot 2016-06-13 at 6 01 51 pm](https://cloud.githubusercontent.com/assets/19908883/16007641/636db04c-3191-11e6-8ab7-45e9b64d282d.png)

Your help much more appreciated.

**Comment by saravnandm** [comment]
Can you send the full log? some of them are not visible. Also did you add any lib/source into pjsip project other than g729?

**Comment by neonsamuel** [comment]
Hello saravanandm,

Thanks for quick reply actually It's my mistake to add into module.

That's why occurring error but I resolve it.

Big Thanks for sharing create Patches.
