### ISSUE TITLE
Call Connected but only one way communication.

### ISSUE THREAD

**Issue by pookie13** [saravanandm/pjsip2.5-g729codec#4]
Hello,
firstly I am very thankful to you for providing the source code of G-729. I have followed your steps and able to build the PJ project with g-729 successfully. I can see the libs being generated for g-729.
I am able to make the call successfully. The caller is receiving the ringing tone  but the caller is not able to hear the called person's voice. 
Can you please suggest the reason behind this problem and also the possible solution. I will be very thankful to you.

**Comment by saravnandm** [comment]
Hi pooki,
Patches are just to build g729 codec lib, To use you need to follow pjsip guidelines. As per my knowledge integrating any codec into pjsua is bit difficult. So i suggest integrate it with pjsip core library and start writing your own sip stack. Come to your problem one way or no audio is mostly NAT problem in your network.
